/* 제목 ID ID ID 내용 작성일*/
SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, LEFT(r.CREATED_DATE,10) FROM USED_GOODS_BOARD as b
INNER JOIN USED_GOODS_REPLY as r ON b.BOARD_ID=r.BOARD_ID
WHERE b.CREATED_DATE LIKE '2022-10%'
ORDER BY r.CREATED_DATE ASC,TITLE ASC;