SELECT i.REST_ID,REST_NAME,FOOD_TYPE,FAVORITES,ADDRESS,ROUND(AVG(review_score),2)
FROM REST_INFO as i
INNER JOIN REST_REVIEW as r ON i.REST_ID=r.REST_ID
GROUP BY i.REST_ID
HAVING address LIKE '서울%'
ORDER BY AVG(review_score) desc,i.FAVORITES desc;